version: '3'

services:
  server:
    image: postgrest/postgrest
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      PGRST_DB_URI: postgres://authenticator:password@db/i
      PGRST_DB_SCHEMA: app
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_JWT_SECRET: 7a42166a63c5747b6e94bea42d5821b1
    depends_on:
      - db

  db:
    image: postgres:11.2-alpine
    restart: unless-stopped
    environment:
      # Change owner of database
      POSTGRES_URI: pg://postgres:password@db/i
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  wait_db:
    image: waisbrot/wait
    environment:
      TARGETS: db:5432

  api:
    image: node:11
    restart: unless-stopped
    user: node
    working_dir: /home/node/app
    environment:
      PGUSER: postgres # change
      PGPASSWORD: password
      PGHOST: db
      PGDATABASE: i
    ports:
      - 5000:5000
    volumes:
      - ./api:/home/node/app
    command: npm start

