version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./config/data/nginx/:/etc/nginx/conf.d
      - ./config/data/certbot/conf:/etc/letsencrypt
      - ./config/data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - server
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./config/data/certbot/conf:/etc/letsencrypt
      - ./config/data/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  server:
    image: postgrest/postgrest
    container_name: server
    restart: unless-stopped
    ports:
      - 4000:3000
    environment:
      PGRST_DB_URI: $PGRST_DB_URI
      PGRST_DB_SCHEMA: $PGRST_DB_SCHEMA
      PGRST_DB_ANON_ROLE: $PGRST_DB_ANON_ROLE
      PGRST_JWT_SECRET: $JWT_SECRET

  api:
    image: node:11
    container_name: api
    restart: unless-stopped
    user: node
    working_dir: /home/node/app
    environment:
      API_DB_URI: $API_DB_URI
      JWT_SECRET: $JWT_SECRET
    ports:
      - 5000:5000
    volumes:
      - ./api:/home/node/app
    command: "/bin/sh -c 'npm ci --production && npm start'"

  metabase:
    image: metabase/metabase:v0.33.0-preview2
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: $POSTGRES_DB
      MB_DB_PORT: $POSTGRES_PORT
      MB_DB_USER: $METABASE_DB_USER
      MB_DB_PASS: $METABASE_DB_PASSWORD
      MB_DB_HOST: $POSTGRES_HOST
      MB_ENCRYPTION_SECRET_KEY: $JWT_SECRET
    ports:
      - 2000:3000
    volumes:
      - ./config/data/metabase:/metabase-data
