version: '3'

services:
  server:
    image: postgrest/postgrest
    restart: unless-stopped
    ports:
      - 4000:3000
    environment:
      PGRST_DB_URI: $PGRST_DB_URI
      PGRST_DB_SCHEMA: $PGRST_DB_SCHEMA
      PGRST_DB_ANON_ROLE: $PGRST_DB_ANON_ROLE
      PGRST_JWT_SECRET: $JWT_SECRET

  api:
    image: node:11
    restart: unless-stopped
    user: node
    working_dir: /home/node/app
    environment:
      API_DB_URI: $API_DB_URI
      JWT_SECRET: $JWT_SECRET
    ports:
      - 5000:5000
    volumes:
      - ./api:/home/node/app
    command: "/bin/sh -c 'npm install && npm start'"

  db:
    image: postgres:11.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:v0.33.0-preview2
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: $POSTGRES_DB
      MB_DB_PORT: $POSTGRES_PORT
      MB_DB_USER: $METABASE_DB_USER
      MB_DB_PASS: $METABASE_DB_PASSWORD
      MB_DB_HOST: $POSTGRES_HOST
      MB_ENCRYPTION_SECRET_KEY: $JWT_SECRET
    ports:
      - 2000:3000
    volumes:
      - ./config/data/metabase:/metabase-data

  wait_db:
    image: waisbrot/wait
    environment:
      TARGETS: db:5432

