version: '3'

services:
  db_check:
    image: hbpmip/pgtap:0.96.0-5
    restart: on-failure
    environment:
      DATABASE: i
      HOST: postgres
      USER: postgres
      PASSWORD: password
      TESTS: /test/**/*.sql -v
    volumes:
      - ./test/:/test/
