version: '3'

services:
  db:
    image: postgres:11.2-alpine
    restart: unless-stopped
    environment:
      # POSTGRES_USER: app_user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: i
    ports:
      - 5432:5432
    volumes:
        - ./data/postgres:/var/lib/postgresql/data

  wait_db:
    image: waisbrot/wait
    environment:
      TARGETS: db:5432
